export {
  DEMO_BASE_PIXELS_PER_UNIT,
  DEMO_MAX_ZOOM,
  DEMO_MIN_ZOOM,
  DEMO_ZOOM_STEP,
  DragDropManager,
  PerformanceMonitor,
  PhysicsEngine,
  Renderer,
  Scene,
  Serializer,
  ThemeManager,
  applyDemoZoomToScene,
  createResetBaselineController,
  getNextDemoZoom,
  getObjectGeometryScale,
  getObjectRealDimension,
  isFieldEnabled,
  isFieldVisible,
  isGeometryDimensionKey,
  parseExpressionInput,
  registry,
  setObjectDisplayDimension,
  setObjectRealDimension,
  syncObjectDisplayGeometry
} from './internal/legacyJsAdapter';
